const scenes=[
{name:"Strange Tracks",cap:"Whoa! Who made THESE tracks?",voice:"Whoa! Hold on, Maya! Look at these tracks! They’re fresh... and they go right into the woods!",speaker:"Benji"},
{name:"Follow the Trail",cap:"Tiptoe... tiptoe... follow those tracks!",voice:"Come on, Maya! Let’s follow them. But remember—stay together and keep a safe distance!",speaker:"Benji"},
{name:"The Missing Tracks",cap:"Poof! The trail disappeared!",voice:"Wait a second... the tracks just vanished! Hmm. Maya, can you spot anything?",speaker:"Benji"},
{name:"The Surprise",cap:"RUSTLE! What was that?!",voice:"Whoa! What was that? ...Oh! It’s a little raccoon! Mystery solved!",speaker:"Benji"},
{name:"Adventure Continues",cap:"Every trail has a story!",voice:"We did it! The mystery is solved. High five, Maya! Where should our next adventure take us?",speaker:"Benji"}];
let i=0,playing=false,elapsed=0,timerId,voices=[];
const $=s=>document.querySelector(s);
function cards(){$("#cards").innerHTML=scenes.map((s,n)=>'<button class="card" data-n="'+n+'"><b>'+String(n+1).padStart(2,"0")+'</b><span>'+s.name+'</span></button>').join("");document.querySelectorAll(".card").forEach((b,n)=>b.onclick=()=>go(n))}
function render(){const s=scenes[i];$("#sceneName").textContent="Scene "+(i+1)+" — "+s.name;$("#caption").textContent=s.cap;$("#voice").textContent=s.voice;document.querySelectorAll(".card").forEach((b,n)=>b.classList.toggle("active",n===i));$("#timer").textContent="0:"+String(Math.min(59,elapsed)).padStart(2,"0")+" / 1:00";$("#titleCard").style.display=i===0&&elapsed<4?"block":"none";$("#maya").style.display=i>=1?"block":"none";$("#raccoon").style.display=i>=3?"block":"none";$("#tracks").innerHTML=i<4?Array.from({length:7},(_,n)=>'<span class="track" style="left:'+((n*13)%90)+'%;bottom:'+(n*13)+'%;animation-delay:'+n*.08+'s"></span>').join(""):"";$("#benji").style.left=[10,24,35,43,56][i]+"%";$("#maya").style.right=[10,17,25,19,27][i]+"%";if(i===3)burst()} 
function burst(){const sc=$("#scene");for(let n=0;n<9;n++){const e=document.createElement("span");e.className="spark";e.textContent=n%2?"✦":"•";e.style.left=(42+Math.random()*25)+"%";e.style.bottom=(28+Math.random()*28)+"%";e.style.animationDelay=(Math.random()*.25)+"s";sc.appendChild(e);setTimeout(()=>e.remove(),1600)}}
function chooseVoice(){voices=speechSynthesis.getVoices();return voices.find(v=>/en-US/i.test(v.lang)&&/Samantha|Google US English|Jenny|Zira|Ava/i.test(v.name))||voices.find(v=>/en-US/i.test(v.lang))||voices.find(v=>/^en/i.test(v.lang))}
function speak(){if(!("speechSynthesis"in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(scenes[i].voice);const v=chooseVoice();if(v)u.voice=v;u.rate=.92;u.pitch=1.18;u.volume=1;speechSynthesis.speak(u)}
if("speechSynthesis"in window)speechSynthesis.onvoiceschanged=()=>{voices=speechSynthesis.getVoices()};
function go(n){i=(n+5)%5;elapsed=i*12;render();if(playing)speak()}
function play(){playing=!playing;$("#playTop").textContent=playing?"❚❚ Pause":"▶ Play Episode";if(playing){if(elapsed>=60){elapsed=0;i=0}render();speak();clearInterval(timerId);timerId=setInterval(()=>{elapsed++;const ni=Math.min(4,Math.floor(elapsed/12));if(ni!==i){i=ni;render();speak()}else render();if(elapsed>=60){clearInterval(timerId);playing=false;$("#playTop").textContent="▶ Replay Episode";speechSynthesis.cancel()}},1000)}else{clearInterval(timerId);speechSynthesis.cancel()}}
$("#playTop").onclick=play;$("#prev").onclick=()=>go(i-1);$("#next").onclick=()=>go(i+1);cards();render();