const scenes=[
{name:"The Footprints",cap:"LUKE: Whoa! What made those tracks?!",fact:"Look at the whole trail before guessing which animal made it.",voice:"Luke: Whoa! What made those tracks?! Lydia: They're fresh. Poppy: And they're heading toward the woods!"},
{name:"Detective Mode",cap:"POPPY: Okay, team... detective mode!",fact:"Animals use trails to find food, water, shelter, and safe routes.",voice:"Poppy: Okay, team... detective mode! We stay together, look carefully, and follow the clues without disturbing anything."},
{name:"A Clever Clue",cap:"POPPY: Count the toes. That changes everything!",fact:"Tracks can show direction, speed, and sometimes how an animal moved.",voice:"Poppy: Count the toes. That changes everything! Lydia: You're right. Luke: So what made them?"},
{name:"The Trail Vanishes",cap:"LYDIA: Wait... where did the tracks go?",fact:"Soft mud, leaves, and changing ground can hide tracks surprisingly fast.",voice:"Lydia: Wait... where did the tracks go? Luke: They just disappeared! Poppy: Nature has a pretty good disappearing trick."},
{name:"RUSTLE!",cap:"POPPY: I knew it! A raccoon!",fact:"Raccoons are mostly active at night and are excellent climbers.",voice:"Poppy: I knew it! A raccoon! Luke: Mystery solved! Lydia: And we found it by watching quietly and giving it space."},
{name:"WildGather Rule",cap:"ALL: Every trail tells a story!",fact:"Watch wildlife quietly, give animals space, and leave no trace.",voice:"Luke: Every trail tells a story! Lydia: Be kind to wildlife. Poppy: And always leave nature better than you found it!"}
];
let i=0,playing=false,elapsed=0,timerId;const $=s=>document.querySelector(s);
function cards(){$("#cards").innerHTML=scenes.map((s,n)=>'<button class="card" data-n="'+n+'"><b>0'+(n+1)+'</b><span>'+s.name+'</span></button>').join("");document.querySelectorAll(".card").forEach((b,n)=>b.onclick=()=>go(n))}
function speak(t){if(!("speechSynthesis"in window))return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.rate=.96;u.pitch=1.12;speechSynthesis.speak(u)}
function render(){let s=scenes[i];$("#sceneName").textContent="Scene "+(i+1)+" — "+s.name;$("#caption").textContent=s.cap;$("#voice").textContent=s.voice;$("#fact b").textContent="🌲 WILD TIP";$("#fact").querySelector("b").nextElementSibling.textContent=s.fact;$("#timer").textContent="0:"+String(elapsed).padStart(2,"0")+" / 1:00";document.querySelectorAll(".card").forEach((b,n)=>b.classList.toggle("active",n===i));$("#titleCard").style.display=i===0&&elapsed<4?"block":"none";$("#raccoon").style.display=i===4?"block":"none";$("#luke").style.left=[8,19,30,41,51,61][i]+"%";$("#lydia").style.right=[8,15,21,27,20,12][i]+"%";$("#poppy").style.left=[42,37,34,38,46,53][i]+"%";$("#tracks").innerHTML=i<4?Array.from({length:i===3?4:9},(_,n)=>'<span class="track" style="left:'+((n*12+6)%88)+'%;bottom:'+(n*10+5)+'%;animation-delay:'+n*.07+'s"></span>').join(""):"";$("#fact").classList.remove("factPop");void $("#fact").offsetWidth;$("#fact").classList.add("factPop");$("#scene").classList.remove("scenePop");void $("#scene").offsetWidth;$("#scene").classList.add("scenePop")}
function go(n){i=(n+6)%6;elapsed=i*10;render();if(playing)speak(scenes[i].voice)}
function play(){playing=!playing;$("#playTop").textContent=playing?"❚❚ Pause":"▶ Play Episode";if(!playing){clearInterval(timerId);speechSynthesis.cancel();return}if(elapsed>=60){elapsed=0;i=0}render();speak(scenes[i].voice);clearInterval(timerId);timerId=setInterval(()=>{elapsed++;if(elapsed>=60){clearInterval(timerId);playing=false;$("#playTop").textContent="▶ Replay Episode";speechSynthesis.cancel();return}let ni=Math.floor(elapsed/10);if(ni!==i){i=ni;speak(scenes[i].voice)}render()},1000)}
$("#playTop").onclick=play;$("#prev").onclick=()=>go(i-1);$("#next").onclick=()=>go(i+1);cards();render();